### PR TITLE
Improvements for Windows version

### PR DESCRIPTION
**Pull request by agustinmista**
This PR implements the features requested in #10:

* The option to enable/disable auto launch at startup 
  + This uses the [auto-launch](https://www.npmjs.com/package/auto-launch) package for cross-platform compatibility.

* A confirmation dialog when the user hits the exit button.
   + Currently this is implemented using a simple native dialog, but having an embedded modal would better for consistency. This requires some extra IPC between the main and renderer process, though.

* Trying to open a second instance of the app now refocus the main window of the existing one instead.

### CODE REVIEW

**Comment by agustinmista** [comment]
Hey @martinhoess!

This is a first attempt at implementing the features you kindly requested in #10. 

Would you mind giving them a try before I merge this PR? You should be able to find the latest build artifact [here](https://github.com/agustinmista/positron/actions/runs/4610665423?pr=11)

**Comment by martinhoess** [comment]
Oh wow!

- The mutex/single instance works
- The question/enquiry before close works

I can't test the Autstart feature until later today, I can't restart my computer at the moment.

**Comment by martinhoess** [comment]
Autostart itself looks good, app got registerd and did start automatically.
The only thing I've found is that the app is registered with the "update.exe" and not with "positron.exe".
Is that intentional?

image

image

**Comment by agustinmista** [comment]
Thanks for testing it out! I'm glad the new features are working. 

As for the Autostart entry, I also noticed that on my PC and, unfortunately, I don't think there's an easy way to fix it. This app uses [Squirrel](https://github.com/Squirrel/Squirrel.Windows) to package the Windows version. Squirrel installs a Update.exe executable that uses to launch Positron indirectly (as you probably noticed by the registry key).

Now, the reason the auto-launch package doesn't add a registry entry calling Positron.exe directly seems related to [this paragraph](https://www.npmjs.com/package/auto-launch#squirrelwindows) of their docs:

> If you're using [Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows), i.e. what's underneath Electron's built-in [autoUpdater](http://electron.atom.io/docs/api/auto-updater/) API on Windows, we add a registry entry for your app's Update.exe instead of your actual application. This is due to how Squirrel.Windows works under the hood. What if we didn't? Well, if the user started / restarted their machine after updating your app, it would launch the old version by mistake.

If you can live with it for now, I'll open an issue and call it a day 😄

**Pull request merged**
